SELECT 
S.SITE_ID as SITE_ID,
S.NAME as SITE_NAME,
IPP.PAYMENT_PLAN_ID,
PP.NAME AS PAYMENT_PLAN_NAME,
MBE.NAME as MASTER_PROGRAM_NAME, B.NAME as PROGRAM_NAME,
R.USER_ID,
R.REGISTRATION_ID,
U.FIRST_NAME,
U.LAST_NAME,
IPP.AMOUNT AS INSTALLMENT_AMOUNT,
date_format(IPP.DUE_DATE,"%m/%d/%y") AS INSTALLMENT_DUE_DATE,
concat(MONTHNAME(IPP.DUE_DATE)," ",YEAR(IPP.DUE_DATE)) AS INSTALLMENT_DUE_MONTH,
case when 
IPP.PAID_ON IS NULL and IPP.DUE_DATE < DATE(NOW()) then "DELINQUENT"
WHEN
IPP.DUE_DATE >= DATE(NOW()) THEN "UPCOMING"
when
IPP.PAID_ON IS NOT NULL THEN "PAID" END AS INSTALLMENT_STATUS,
CASE WHEN 
IPP.IS_PAID = 1 THEN "YES"
ELSE "NO" END AS IS_PAID,
case when I.DISABLE_AUTO_PAY > 0 then "NO" ELSE "YES" END AS "Auto-Pay" 
FROM INVOICE_PP_INSTALLMENT IPP
INNER JOIN INVOICE I ON I.INVOICE_ID = IPP.INVOICE_ID
INNER JOIN SITE S ON S.SITE_ID = IPP.SITE_ID
INNER JOIN PAYMENT_PLAN PP ON PP.PAYMENT_PLAN_ID = IPP.PAYMENT_PLAN_ID
INNER JOIN BASE_EVENT B ON PP.BASE_EVENT_ID = B.BASE_EVENT_ID
INNER JOIN REGISTRATION R ON R.INVOICE_ID = I.INVOICE_ID
LEFT JOIN BASE_EVENT MBE on B.MASTER_BASE_EVENT_ID = MBE.BASE_EVENT_ID
INNER JOIN USER U ON U.USER_ID = R.USER_ID
WHERE S.ORG_ACCOUNT_ID IN (27814)
ORDER BY IPP.DUE_DATE DESC